const imagePrompt = [
  "A Cyberpunk Street, Pixel Art, At Midnight, With Neon Lights",
  "A Haunted Library, Fantasy Art, In A Parallel Universe, With Floating Books",
  "An Ice Dragon, Oil Painting, In The Arctic, With Glowing Crystals",
  "A Samurai Warrior, Vaporwave, In A Futuristic Tokyo, With Laser Katanas",
  "A Floating Island, Watercolor, In The Sky, With Waterfalls",
  "An Ancient Robot, 3D Render, Buried In A Jungle, With Vines",
  "A Fairy Village, Fantasy Art, Inside A Giant Tree, With Fireflies",
  "A Mech Battle, Low Poly, In A Desert, With Dust Storms",
  "A Portal, Oil Painting, In The Middle Of The Ocean, With Lightning",
  "A Giant Whale, Pixel Art, Flying In The Sky, With Planets Around",
  "A Vampire Castle, Gothic Style, At Dusk, With Fog",
  "A Neon Forest, 3D Render, On Another Planet, With Bioluminescent Trees",
  "A Spaceship Launch, Watercolor, At Sunrise, With Reflections",
  "An Alien Bazaar, Fantasy Art, On Mars, With Alien Creatures",
  "A Wizard, Oil Painting, Casting A Spell, With Time Freeze Effect",
  "A Robot Dog, Low Poly, In A Cyber City, With Glowing Eyes",
  "A Galaxy, Vaporwave, Forming A Spiral, With Bright Colors",
  "A Mystic Portal, Pixel Art, In A Dungeon, With Glowing Stones",
  "A Futuristic Motorcycle, 3D Render, Racing Through Rain, With Light Trails",
  "A Dream Garden, Fantasy Art, At Night, With Shooting Stars",
  "A Supernova, Digital Art, Exploding In Space, With Energy Waves",
  "A Floating Book, Watercolor, In A Dark Room, With Magic Symbols",
  "A Crystal Ship, Sci-Fi Style, In Deep Space, With Glowing Sails",
  "A Dystopian Bridge, Pixel Art, In A Foggy City, With Drones Flying",
  "A Ghost Pirate Ship, Oil Painting, On Stormy Seas, With Lightning Bolts",
  "A Submarine, 3D Render, In A Coral Reef, With Glowing Fish",
  "A Tiny Planet, Low Poly, Floating In Space, With A Single Tree",
  "A Magical Deer, Fantasy Art, In A Winter Forest, With Northern Lights",
  "A Digital Forest, Vaporwave, Made Of Code, With Pixelated Trees",
  "A Floating Temple, Watercolor, Over A Waterfall, With Rainbow Mist",
  "A Ninja, Pixel Art, On A Rooftop, With Moonlight Shadows",
  "A Lava Golem, Oil Painting, Emerging From A Volcano, With Smoke",
  "A Time Machine, 3D Render, In A Lab, With Lightning Effects",
  "A Sky Whale, Fantasy Art, Above The Clouds, With Rainbow Trails",
  "An AI God, Sci-Fi Style, In A Digital Heaven, With Data Streams",
  "A Jungle Robot, Vaporwave, Covered In Moss, With LED Eyes",
  "A Fire Wizard, Oil Painting, In Battle, With Flaming Runes",
  "A Moon Base, 3D Render, With Solar Panels, Under Earthlight",
  "A Cosmic Tree, Fantasy Art, Rooted In A Nebula, With Stars",
  "A Dragon Egg, Pixel Art, In A Nest Of Flames, With Magical Symbols",
  "A Desert Tower, Watercolor, Alone In Sand Dunes, With A Lonely Flag",
  "A Hacker, Cyberpunk Style, Inside The Matrix, With Code Falling",
  "A Puppet Master, Oil Painting, In A Shadowy Theater, With Strings Of Light",
  "A Time Rift, Fantasy Art, Splitting A City, With Floating Debris",
  "A Neon Samurai, Pixel Art, On A Hoverboard, With Night Skyline",
  "A Mirror World, Watercolor, Reflecting Opposites, With Faded Colors",
  "A Giant Robot, 3D Render, Guarding A Mountain, With Birds Flying",
  "A Solar Eclipse, Fantasy Art, Turning Day Into Night, With Magic Beams",
  "A Cyber Tree, Pixel Art, In A Server Farm, With Glitch Effects",
  "A Shipwreck, Oil Painting, Underwater, With Glowing Sea Creatures",
  "A Magical Clock Tower, Fantasy Art, In A Floating City, With Spinning Gears",
  "A Steampunk Airship, Detailed Illustration, Soaring Over Victorian London, With Gears Turning",
  "A Bioluminescent Cave, Digital Painting, With Shimmering Fungi, And Crystal Formations",
  "An Ancient Spaceship, Concept Art, Buried On An Alien Planet, With Overgrown Flora",
  "A Quantum City, Abstract Art, With Intersecting Dimensions, And Shifting Architecture",
  "A Ghostly Train, Gothic Art, Speeding Through A Moonlit Forest, With Ethereal Smoke",
  "A Desert Oasis, Realistic Render, Under A Double Sunset, With Ancient Ruins",
  "A Cosmic Serpent, Stained Glass Style, Winding Through Nebulae, With Glittering Scales",
  "A Sunken City, Digital Art, In The Deep Ocean, With Schools Of Luminous Fish",
  "A Futuristic Farm, Isometric View, With Automated Harvesters, And Hydroponic Towers",
  "A Whispering Woods, Fantasy Art, At Twilight, With Animated Trees And Faeries",
  "A Volcanic Planet, Sci-Fi Style, With Lava Rivers, And Obsidian Structures",
  "A Clockwork Beast, Steampunk, Roaming A Grassy Plain, With Intricate Mechanisms",
  "A Cybernetic Animal, Mixed Media, In A City Alleyway, With Neon Graffiti",
  "A Glacial Metropolis, Architectural Render, Carved Into Icebergs, With Northern Lights",
  "A Dream Weaver, Surrealism, Creating Universes With Threads Of Light",
  "An Elemental Golem, Fantasy Art, Formed From Earth And Fire, In A Canyon",
  "A Time-Traveling Bookstore, Whimsical Illustration, With Books From All Eras",
  "A Celestial Map, Antique Style, Unfurling In Space, With Constellations",
  "A Robotic Gardener, Anime Style, Tending A Lush Botanical Garden, With Glowing Plants",
  "A Floating Marketplace, Fantasy Art, Over A Busy Harbor, With Hot Air Balloons",
  "A Data Stream Waterfall, Digital Art, Cascading Through A Server Farm, With Binary Code",
  "A Haunted Mansion, Victorian Style, On A Stormy Night, With Flickering Lights",
  "An Underwater Spaceship, Sci-Fi Art, Exploring An Alien Ocean, With Strange Lifeforms",
  "A Forest Spirit, Folk Art, Protecting Ancient Trees, With Glowing Eyes",
  "A Post-Apocalyptic City, Gritty Art, Reclaimed By Nature, With Overgrown Skyscrapers",
  "A Giant Megalith, Ancient Style, Covered In Runes, Under A Stormy Sky",
  "A Starship Graveyard, Concept Art, On A Barren Moon, With Distant Nebulae",
  "A Bioluminescent Jungle, Digital Painting, At Night, With Glowing Flora And Fauna",
  "A Sky Pirate Ship, Illustration, With Tattered Sails, Flying Through Clouds",
  "A Living City, Organic Architecture, Built Into A Giant Tree, With Root Systems",
  "A Cosmic Library, Abstract Art, With Books Made Of Starlight, And Floating Galaxies",
  "An Enchanted Forge, Fantasy Art, With Molten Gold And Glowing Anvils",
  "A Dystopian Subway, Gritty Realism, Abandoned And Overgrown, With Flickering Lights",
  "A Time Loop, Surrealism, Showing Repeating Moments, With Fading Colors",
  "A Mech-Operated Farm, Steampunk, With Steam-Powered Tractors, In A Rolling Field",
  "A Cloud Serpent, Ink Wash Painting, Winding Through Mountains, With Misty Vistas",
  "A Cybernetic Monk, Digital Art, Meditating In A Holographic Temple, With Code Stream",
  "An Alien Ocean City, Sci-Fi, Built On Giant Kelp Forests, With Floating Platforms",
  "A Whispering Waterfall, Fantasy Art, With Ancient Symbols Carved In Stone, And Glowing Water",
  "A Future Slum, Cyberpunk, With Stacked Buildings And Grimy Alleyways",
  "A Robotic Animal Sanctuary, Concept Art, In A Desert, With Solar-Powered Shelters",
  "A Dream Portal, Psychedelic Art, Opening In A Forest, With Swirling Colors",
  "An Interdimensional Train Station, Abstract, With Multiple Entrances To Different Realities",
  "A Bioluminescent Swamp, Digital Painting, At Night, With Fireflies And Glowing Frogs",
  "A Floating Arena, Gladiator Style, In The Sky, With Chains And Spectators",
  "A City of Bridges, Architectural Design, Spanning A Vast Canyon, With Intricate Arches",
  "A Space Nomad Camp, Realistic Render, On An Arid Planet, With Dome Tents",
  "A Data Fortress, Sci-Fi, Hidden Deep Within A Mountain, With Server Racks And Glowing Screens",
  "A Giant Clockwork Heart, Steampunk, Powering A Floating Island, With Gears And Steam",
  "A Fungal Forest, Fantasy Art, With Giant Mushrooms And Bioluminescent Spores",
];
